import React from 'react'
import styles from "../../styles/Story.module.css"
import Nav from '@/src/BigComponents/Navigation/Nav'
import Footer from '@/src/BigComponents/Footer/Footer'
import Head from 'next/head'
import Image from 'next/image'
import EditorJsTransformer from '@/src/EditorJsTransformer/EditorJsTransformer'

export default function story(props) {
    const story = props.story.attributes;
    const inhalt = JSON.parse(story.Content);

    console.log(inhalt);

    return (
        <>
            <Head>
                <title>MPG Oberstufe - Eine Seite von Schüler für Schüler</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Nav />

            <div className={styles.singleStory}>
                <div className={styles.innerDiv}>
                    <div className={styles.image} style={{ backgroundImage: `url("${story.Bild.data.attributes.url}")` }}></div>

                    <div className={styles.content}>
                        <div className={styles.top}>
                            <div className={styles.user}>
                                <div className={styles.iconDiv}>
                                    <div className={styles.icon} style={{ backgroundImage: `url('${story.Autor.data.attributes.Bild.data.attributes.url}')` }}></div>
                                </div>
                                <div className={styles.info}>
                                    <div>
                                        <p>{story.Autor.data.attributes.Name}</p>
                                        <span>{story.Autor.data.attributes.Klasse}. Klasse</span>
                                    </div>
                                </div>
                            </div>

                            <div className={styles.copyLink}>
                                <Image src="/images/copyLink.svg" width="26" height="26" />
                            </div>
                        </div>

                        <div className={styles.bottom}>
                            <span>{new Date(story.publishedAt).toLocaleDateString("default", {
                                day: "2-digit",
                                month: "2-digit",
                                year: "numeric"
                            })}</span>
                            <h1>{story.Titel}</h1>

                            <EditorJsTransformer inhalt={inhalt} />

                        </div>
                    </div>
                </div>
            </div>

            <Footer />
        </>
    )
}

export async function getServerSideProps(context) {
    const slug = context.params.story;

    const res = await fetch(`${process.env.STRAPI_URL}/api/stories?filters[Slug][$eq]=${slug}&populate[Bild][true]&populate[Autor][populate][Bild][true]`)
    const stories = await res.json()

    return {
        props: {
            story: stories.data[0]
        },
    }
}