import Head from 'next/head'
import React from 'react'
import styles from "../../styles/Dateien.module.css"
import TitleBar from '@/src/SmallComponents/TitleBar'
import Nav from '@/src/BigComponents/Navigation/Nav'
import Footer from '@/src/BigComponents/Footer/Footer'
import OneAg from '@/src/SmallComponents/OneAg/OneAg'
import NoAg from '@/src/SmallComponents/OneAg/NoAg'

export default function dateien(props) {
    const ags = props.ags ? props.ags : [];

    return (
        <>
            <Head>
                <title>MPG Oberstufe - Eine Seite von Schüler für Schüler</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Nav />

            <div className={styles.dateienCtn}>
                <div className={styles.left}>
                    <TitleBar top="0">AGs an unserer Schule</TitleBar>

                    <div className={styles.ags}>
                        {ags.length > 0 ? ags.map(e => {
                            return (
                                <OneAg data={e} key={e.id} />
                            )
                        }) : <>
                            <NoAg />
                            <NoAg />
                            <NoAg />
                        </>}
                    </div>
                </div>

                <div className={styles.right}>
                    <TitleBar top="0">Wichtige Ressourcen</TitleBar>
                </div>
            </div>

            <Footer />
        </>
    )
}

export async function getServerSideProps() {

    const res3 = await fetch(`${process.env.STRAPI_URL}/api/ags?pagination[start]=0&pagination[limit]=6`)
    const ags = await res3.json()

    return {
        props: {
            ags: ags.data,
        },
    }
}
