import Head from 'next/head'
import React from 'react'
import styles from "../../styles/Termin.module.css"
import MainSide from '@/src/MainSide'
import LinkUnderline from '@/src/SmallComponents/LinkUnderline';
import EditorJsTransformer from '@/src/EditorJsTransformer/EditorJsTransformer';

export default function termin(props) {
    const sidebar = props.sidebar;
    const termin = props.termin.attributes
    const inhalt = JSON.parse(termin.Inhalt);

    return (
        <>
            <Head>
                <title>MPG Oberstufe - Eine Seite von Schüler für Schüler</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <MainSide sidebar={sidebar} noTermine>
                <div className={styles.dateTitle}>
                    <div className={styles.date}>
                        <div>{new Date(termin.Datum).toLocaleDateString("default", {
                            day: "2-digit"
                        })}</div>
                        <span>{new Date(termin.Datum).toLocaleDateString("default", {
                            month: "long"
                        })}</span>
                    </div>

                    <div className={styles.info}>
                        <div>
                            <h1>{termin.Bezeichnung}</h1>
                        </div>
                    </div>
                </div>

                <EditorJsTransformer inhalt={inhalt} />

                <LinkUnderline href="/termine">Alle Termine</LinkUnderline>
            </MainSide>
        </>
    )
}

export async function getServerSideProps(context) {
    const slug = context.params.termin;

    const resTermine = await fetch(`${process.env.STRAPI_URL}/api/termine?filters[Slug][$eq]=${slug}`)
    const termine = await resTermine.json()

    const res2 = await fetch(`${process.env.HOSTING_DOMAIN}/api/sidebar`);
    const sidebar = await res2.json()

    return {
        props: {
            termin: termine.data[0],
            sidebar
        },
    }
}