import MainSide from '@/src/MainSide';
import OneDate from '@/src/SmallComponents/OneDate/OneDate';
import TitleBar from '@/src/SmallComponents/TitleBar';
import Head from 'next/head';
import React from 'react'

export default function termine(props) {
    const termine = props.termine ? props.termine : [];
    const sidebar = props.sidebar;

    return (
        <>
            <Head>
                <title>MPG Oberstufe - Eine Seite von Schüler für Schüler</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <MainSide sidebar={sidebar}>
                <TitleBar top="0">Unsere Termine</TitleBar>

                {termine.length > 0 ? <>
                    {termine.map(e => {
                        return (
                            <OneDate data={e} key={e.id} />
                        )
                    })}
                </> : <>Etwas ist schiefgelaufen...</>}
            </MainSide>
        </>
    )
}

export async function getServerSideProps() {
    const resTermine = await fetch(`${process.env.STRAPI_URL}/api/termine?sort=Datum:desc`)
    const termine = await resTermine.json()

    const res2 = await fetch(`${process.env.HOSTING_DOMAIN}/api/sidebar`);
    const sidebar = await res2.json()

    return {
        props: {
            termine: termine.data,
            sidebar
        },
    }
}