import MainSide from '@/src/MainSide'
import OneImage from '@/src/SmallComponents/OneImage/OneImage';
import React from 'react'
import styles from "../styles/Galerie.module.css"
import TitleBar from '@/src/SmallComponents/TitleBar';
import Head from 'next/head';

export default function galerie(props) {
    const bilder = props.bilder ? props.bilder : [];
    const sidebar = props.sidebar;

    return (
        <>
            <Head>
                <title>MPG Oberstufe - Eine Seite von Schüler für Schüler</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <MainSide sidebar={sidebar} noPic>
                <TitleBar top="0">Unsere Galerie</TitleBar>

                <div className={styles.galerie}>
                    {bilder.length > 0 ? bilder.map(e => {
                        return (
                            <OneImage data={e} key={e.id} />
                        )
                    }) : <>Etwas ist schiefgelaufen...</>}
                </div>
            </MainSide>
        </>
    )
}

export async function getServerSideProps() {
    const resBilder = await fetch(`${process.env.STRAPI_URL}/api/bilder?populate[Bild][true]&populate[Autor][populate][Bild][true]&sort=publishedAt:desc`)
    const bilder = await resBilder.json()

    const res2 = await fetch(`${process.env.HOSTING_DOMAIN}/api/sidebar`);
    const sidebar = await res2.json()

    return {
        props: {
            bilder: bilder.data,
            sidebar
        },
    }
}