import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import MainSide from '@/src/MainSide'
import TitleBar from '@/src/SmallComponents/TitleBar'
import OneStory from '@/src/SmallComponents/OneStory/OneStory'
import NoStory from '@/src/SmallComponents/OneStory/NoStory'
import LinkUnderline from '@/src/SmallComponents/LinkUnderline'
import OneArticle from '@/src/SmallComponents/OneArticle/OneArticle'
import NoArticle from '@/src/SmallComponents/OneArticle/NoArticle'
import OneAg from '@/src/SmallComponents/OneAg/OneAg'
import NoAg from '@/src/SmallComponents/OneAg/NoAg'

export default function Home(props) {
    const posts = props.posts ? props.posts : [];
    const articles = props.articles ? props.articles : [];
    const ags = props.ags ? props.ags : [];

    return (
        <>
            <Head>
                <title>MPG Oberstufe - Eine Seite von Schüler für Schüler</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <MainSide sidebar={props.sidebar}>
                <TitleBar top="0">Stories aus der Oberstufe</TitleBar>

                <div className={styles.stories}>
                    {posts[0] ? <div><OneStory data={posts[0]} /> <LinkUnderline href="/stories" top="40">Alle ansehen</LinkUnderline> </div> : <NoStory />}
                    <div className={styles.right}>
                        {posts[1] ? <OneStory data={posts[1]} small /> : <NoStory />}
                        <div className={styles.space}></div>
                        {posts[2] ? <OneStory data={posts[2]} small /> : <NoStory />}
                    </div>
                </div>


                <TitleBar>Aus unserer Schülerzeitung</TitleBar>

                <div className={styles.articles}>
                    {articles.length > 0 ? articles.map(e => {
                        return (
                            e ? <OneArticle key={e.id} data={e} /> : <NoArticle />
                        )
                    }) : <>
                        <NoArticle />
                        <NoArticle />
                    </>}

                    <LinkUnderline href="/schuelerzeitung" top="38">Alle ansehen</LinkUnderline>
                </div>


                <TitleBar>Ags an unserer Schule</TitleBar>

                <div className={styles.ags}>
                    <div className={styles.agsDiv}>
                        {ags.length > 0 ? ags.map(e => {
                            return (
                                <OneAg data={e} key={e.id} />
                            )
                        }) : <>
                            <NoAg />
                            <NoAg />
                            <NoAg />
                        </>}
                    </div>

                    <LinkUnderline href="/ags" top="38">Alle ansehen</LinkUnderline>
                </div>
            </MainSide>
        </>
    )
}

export async function getServerSideProps() {
    const res = await fetch(`${process.env.STRAPI_URL}/api/stories?populate[Bild][true]&pagination[start]=0&pagination[limit]=3&populate[Autor][populate][Bild][true]&sort=publishedAt:desc`)
    const posts = await res.json()

    const res2 = await fetch(`${process.env.STRAPI_URL}/api/zeitungs?populate=Bild&pagination[start]=0&pagination[limit]=3&sort=publishedAt:desc`)
    const articles = await res2.json()

    const res3 = await fetch(`${process.env.STRAPI_URL}/api/ags?pagination[start]=0&pagination[limit]=6`)
    const ags = await res3.json()

    const res4 = await fetch(`${process.env.HOSTING_DOMAIN}/api/sidebar`);
    const sidebar = await res4.json()

    return {
        props: {
            posts: posts.data,
            articles: articles.data,
            ags: ags.data,
            sidebar
        },
    }
}
