import MainSide from '@/src/MainSide'
import Head from 'next/head';
import React from 'react'
import styles from "../../styles/Zeitung.module.css"
import EditorJsTransformer from '@/src/EditorJsTransformer/EditorJsTransformer';
import LinkUnderline from '@/src/SmallComponents/LinkUnderline';
import TitleBar from '@/src/SmallComponents/TitleBar';

export default function artikel(props) {
    const sidebar = props.sidebar;
    const article = props.article.attributes;
    const inhalt = JSON.parse(article.Artikel);

    return (
        <>
            <Head>
                <title>MPG Oberstufe - Eine Seite von Schüler für Schüler</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <MainSide sidebar={sidebar} >
                <TitleBar top="0">Unsere Schülerzeitung</TitleBar>
                <div className={styles.artikel}>
                    <div className={styles.image} style={{ backgroundImage: `url("${article.Bild.data.attributes.url}")` }}></div>

                    <div className={styles.innerDiv}>
                        <span>{new Date(article.publishedAt).toLocaleDateString("default", {
                            day: "2-digit",
                            month: "2-digit",
                            year: "numeric"
                        })}</span>
                        <h1>{article.Titel}</h1>

                        <EditorJsTransformer inhalt={inhalt} />

                        <LinkUnderline href="/schuelerzeitung">Weitere Artikel lesen</LinkUnderline>
                    </div>
                </div>
            </MainSide>
        </>
    )
}

export async function getServerSideProps(context) {
    const slug = context.params.artikel;

    const res = await fetch(`${process.env.STRAPI_URL}/api/zeitungs?filters[Slug][$eq]=${slug}&populate=Bild&pagination[start]=0&pagination[limit]=3&sort=publishedAt:desc`)
    const article = await res.json()

    const res2 = await fetch(`${process.env.HOSTING_DOMAIN}/api/sidebar`);
    const sidebar = await res2.json()

    return {
        props: {
            article: article.data[0],
            sidebar
        },
    }
}