import MainSide from '@/src/MainSide'
import NoArticle from '@/src/SmallComponents/OneArticle/NoArticle';
import OneArticle from '@/src/SmallComponents/OneArticle/OneArticle';
import TitleBar from '@/src/SmallComponents/TitleBar'
import Head from 'next/head'
import React from 'react'
import styles from "../../styles/Zeitung.module.css"

export default function schuelerzeitung(props) {
    const articles = props.articles ? props.articles : [];
    const sidebar = props.sidebar;

    return (
        <>
            <Head>
                <title>MPG Oberstufe - Eine Seite von Schüler für Schüler</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <MainSide sidebar={sidebar}>
                <TitleBar top="0">Unsere Schülerzeitung</TitleBar>

                <div className={styles.articles}>
                    {articles.length > 0 ? articles.map(e => {
                        return (
                            e ? <OneArticle key={e.id} data={e} /> : <NoArticle />
                        )
                    }) : <>
                        <NoArticle />
                        <NoArticle />
                    </>}
                </div>
            </MainSide>
        </>
    )
}

export async function getServerSideProps() {
    const res = await fetch(`${process.env.STRAPI_URL}/api/zeitungs?populate=Bild&sort=publishedAt:desc`)
    const articles = await res.json()

    const res2 = await fetch(`${process.env.HOSTING_DOMAIN}/api/sidebar`);
    const sidebar = await res2.json()

    return {
        props: {
            articles: articles.data,
            sidebar
        },
    }
}